#!/bin/bash
###############################################################################
#
#    ZEVENET Software License
#    This file is part of the ZEVENET Load Balancer software package.
#
#    Copyright (C) 2014-today ZEVENET SL, Sevilla (Spain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

# Save zlb-stop and zlb-start to a temporal directory
tmp_start="/tmp/zlb-start"
tmp_stop="/tmp/zlb-stop"
zvn_start="/usr/local/zevenet/config/zlb-start"
zvn_stop="/usr/local/zevenet/config/zlb-stop"

if [ -f $zvn_start ]; then
	mv $zvn_start $tmp_start
fi

if [ -f $zvn_stop ]; then
	mv $zvn_stop $tmp_stop
fi

# Create the new GUI system group
groupadd -f webgui;
usermod -a -G webgui root;

