#!/usr/bin/perl

use warnings;
use Regexp::IPv6 qw($IPv6_re);

# BASICS
our $newline   = qr/\n/;
our $startline  = qr/^\^/;

# MACROS
our $word_prefix   = '[?[\w-\s]+]?';
our $port_interval = "1,65535";
our $UNSIGNED8BITS = '(?:25[0-5]|2[0-4]\d|(?!0)[1]?\d\d?|0)';         # (0-255)
our $UNSIGNED7BITS = '(?:[0-9]{1,2}|10[0-9]|11[0-9]|12[0-8])';        # (0-128)
our $HEXCHAR       = qr/(?:[A-Fa-f0-9])/;
our $ipv4_addr     = qr/(?:$UNSIGNED8BITS\.){3}$UNSIGNED8BITS/;
our $ipv6_addr     = $IPv6_re;
our $mac_addr      = qr/(?:$HEXCHAR$HEXCHAR\:){5}$HEXCHAR$HEXCHAR/;
our $ipv4v6        = qr/(?:$ipv4_addr|$ipv6_addr)/;
our $boolean       = qr/(?:true|false)/;
our $integer       = qr/\d+/;
our $natural = qr/[1-9]\d*/;    # natural number = {1, 2, 3, ...}
our $weekdays =
  qr/(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)/;
our $minutes    = qr/(?:\d|[0-5]\d)/;
our $hours      = qr/(?:\d|[0-1]\d|2[0-3])/;
our $months     = qr/(?:[1-9]|1[0-2])/;
our $dayofmonth = qr/(?:[1-9]|[1-2]\d|3[01])/;    # day of month

our $hostname = qr/[a-z][a-z0-9\-]{0,253}[a-z0-9]/;
our $domain   = qr/(?:$hostname\.)+[a-z]{2,}/;

our $vlan_tag    = qr/\d{1,4}/;
our $virtual_tag = qr/[a-zA-Z0-9\-]{1,13}/;
our $nic_if      = qr/[a-zA-Z0-9\-]{1,15}/;
our $bond_if     = qr/[a-zA-Z0-9\-]{1,15}/;
our $vlan_if     = qr/[a-zA-Z0-9\-]{1,13}\.$vlan_tag/;
our $interface   = qr/$nic_if(?:\.$vlan_tag)?(?:\:$virtual_tag)?/;
our $port_range =
  qr/(?:[1-9]\d{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])/;

our $blacklists_source = qr{(?:\d{1,3}\.){3}\d{1,3}(?:\/\d{1,2})?};

our $email = qr/^(?:[a-zA-Z][\w\_\.]+)\@(?:[a-zA-Z0-9.-]+)\.(?:[a-zA-Z]{2,4})$/;

# generic types
our $natural_num = $natural;

#zapi
our $zapi_key = qr/[a-zA-Z0-9]+/;

# common
our $port = $port_range;
our $multiport =
  qr/(?:\*|(?:$port_range|$port_range\:$port_range)(?:,$port_range|,$port_range\:$port_range)*)/;
our $user = qr/[\w]+/;
our $url = qr/(http|https):\/\/([^\/]+)(.*)/;

# system
our $dns_nameserver = $ipv4v6;
our $dns            = qr/(?:primary|secondary)/;
our $ssh_port       = $port_range;
our $ssh_listen     = qr/(?:$ipv4v6|\*)/;
our $snmp_port      = $port_range;
our $snmp_scope     = qr{(?:\d{1,3}\.){3}\d{1,3}\/\d{1,2}};    # ip/mask
our $ntp            = qr{[\w\.\-]+};
our $http_proxy = qr{\S*};    # use any character except the spaces
our $rsyslog_remote = qr/(?:$ipv4v6|$hostname|$domain)/;    


# farms
our $farm_name = qr/[a-zA-Z0-9\-]+/;
our $farm_name_format =
  "The farm name accepts alphabet letters, numbers or hypens (-).";
our $http_service = qr/[a-zA-Z0-9\-]+/;
our $gslb_service = qr/[a-zA-Z0-9][\w\-]*/;

# backup
our $backup = qr/[\w-]+/;

# http
our $http_sts_timeout = qr/(?:\d+)/;

# GSLB
our $zone          = qr/(?:$hostname\.)+[a-z]{2,}/;
our $resource_name = qr/(?:[\w\-\.]+|\@)/;
our $resource_ttl  = qr/$natural/;                    # except zero
our $resource_type =
  qr/(?:NS|A|AAAA|CNAME|DYNA|MX|SRV|TXT|PTR|NAPTR)/;    # not used from API 4

# interfaces ( WARNING: length in characters < 16  )
our $nic_interface    = $nic_if;
our $bond_interface   = $bond_if;
our $vlan_interface   = $vlan_if;
our $virt_interface   = qr/(?:$bond_if|$nic_if)(?:\.$vlan_tag)?:$virtual_tag/;
our $routed_interface = qr/(?:$nic_if|$bond_if|$vlan_if)/;

# notifications
our $notif_time = $natural;                             # this value can't be 0

# IPDS
# blacklists
our $blacklists_name = qr{\w+};
our $blacklists_url  = qr{.+};
our $blacklists_day  = qr{(:?$dayofmonth|$weekdays)};

# DoS
our $dos_name = qr/[\w]+/;

# RBL
our $rbl_name   = qr/[\w]+/;
our $rbl_domain = qr/[\w\.\-]+/;

# WAF
our $waf_set_name   = qr/[\.\w-]+/;
our $waf_rule_id    = qr/\d+/;
our $waf_severity   = qr/[0-9]/;
our $waf_phase      = qr/(?:[1-5]|request|response|logging)/;
our $waf_log        = qr/(?:$boolean|)/;
our $waf_audit_log  = qr/(?:$boolean|)/;
our $waf_skip       = qr/[0-9]+/;
our $waf_skip_after = qr/\w+/;

# certificates filenames
our $certificate_name = qr/(?:\*[_|\.])?\w[\w\.\(\)\@ \-]*/;
our $certificate      = qr/$certificate_name\.(?:pem|csr)/;
our $cert_pem         = qr/$certificate_name\.pem/;
our $cert_name        = qr/[a-zA-Z0-9\-]+/;
our $le_mail          = $email;

# IPS
our $IPv4_addr = qr/$ipv4_addr/;
our $ip_addr   = $ipv4v6;
our $ip_mask   = qr/(?:$ipv4_addr|$UNSIGNED7BITS)/;

# farm guardian
our $fg_name = qr/[\w-]+/;

# RBAC
our $user_name     = qr/[a-z][-a-z0-9_.]+/;
our $rbac_password = qr/(?=.*[0-9])(?=.*[a-zA-Z]).{8,512}/;
our $group_name    = qr/[\w-]+/;
our $role_name     = qr/[\w-]+/;

# alias
our $alias_id        = qr/(?:$ipv4v6|$interface)/;
our $alias_backend   = qr/$ipv4v6/;
our $alias_interface = qr/$interface/;
our $alias_name      = qr/(?:$zone|[\w-]+)/;
our $alias_id_re     = qr/(?:$alias_interface|$alias_backend)/;

# routing
our $routingRulePrioUserMin = "29000";
our $routingRulePrioUserMax = "30999";

# vpn
our $vpn_name = qr/[a-zA-Z][a-zA-Z0-9\-]*/;
our $vpn_user = qr/[a-zA-Z][a-zA-Z0-9\-]*/;
